RAILS-5-NA-PRATICA/app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  resources :categories
  resources :bills

  root 'dashboard#index'
end

RAILS-5-NA-PRATICA/app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

RAILS-5-NA-PRATICA/app/app/models/bill.rb
class Bill < ApplicationRecord
    belongs_to :category
    has_attached_file :image 
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

RAILS-5-NA-PRATICA/app/app/models/category.rb
class Category < ApplicationRecord
    has_many :bills
end

RAILS-5-NA-PRATICA/app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

RAILS-5-NA-PRATICA/app/app/controllers/bills_controller.rb
class BillsController < ApplicationController
    before_action :set_bill, only:[:edit, :update, :destroy]
    def index
        @bills = Bill.all
    end

    def new
        @bill = Bill.new
        @categories = Category.all
    end

    def edit
        @categories = Category.all        
    end
    def create
        @bill = Bill.new(bills_params)
        respond_to do |format|
            if @bill.save
                format.html { redirect_to bills_url }
            end
        end
    end

    def update
        respond_to do |format|
            if(@bill.update(bills_params))
                format.html { redirect_to bills_url}
            end
        end
    end

    def destroy
        @bill.destroy

        respond_to do |format|
            format.html { redirect_to bills_url }
        end
    end

    private
        def bills_params
            params.require(:bill).permit(:name, :value, :category_id, :image)
        end

        def set_bill
            @bill = Bill.find(params[:id])
        end
end

RAILS-5-NA-PRATICA/app/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:edit,:update,:destroy]

    def index
        @categories  = Category.all
    end

    def new
        @category = Category.new
    end

    def edit

    end

    def create
        @category = Category.new(category_params)

        respond_to do |format|
            if @category.save
                format.html { redirect_to categories_url }
            end
        end
    end

    def update
        respond_to do |format|
            if @category.update(category_params)
                format.html { redirect_to categories_url }
            end
        end    
    end

    def destroy
        @category.destroy

        respond_to do |format|
            format.html { redirect_to categories_url }
        end
    end

    private
        def set_category
            @category = Category.find(params[:id])
        end

        def category_params
            params.require(:category).permit(:name, :desc)
        end
end

RAILS-5-NA-PRATICA/app/app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    def index
        @bills = Bill.all
    end
end

RAILS-5-NA-PRATICA/app/app/helpers/application_helper.rb
module ApplicationHelper
end

RAILS-5-NA-PRATICA/app/app/helpers/bills_helper.rb
module BillsHelper
end

RAILS-5-NA-PRATICA/app/app/helpers/categories_helper.rb
module CategoriesHelper
end

RAILS-5-NA-PRATICA/app/app/helpers/dashboard_helper.rb
module DashboardHelper
end

RAILS-5-NA-PRATICA/app/app/views/bills/_form.html.erb
<%= form_for @bill, html: { class: 'form', multipart: true} do |f| %>
    <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :value %>
        <%= f.number_field :value, class: 'form-control', step: :any %>
    </div>
    <div class="form-group">
        <%= f.label :category_id %>
        <%= collection_select(:bill, :category_id, @categories, :id, :name, {}, {:class => 'form-control'})%>
    </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.file_field :image %>
    </div>
    <div class="form-group">
            <%= f.submit 'Save', :class => 'btn btn-success' %>
    </div>

<% end %>

RAILS-5-NA-PRATICA/app/app/views/bills/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Edit</h4>
    </div>

    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/bills/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Bills</h4>    
    </div>
    <div class="panel-body">
        <%= link_to 'New Bill', new_bill_path ,class: 'btn btn-primary'%>
        <div class="table-responsive">
            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Value</th>
                    <th>Category</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @bills.each do |bill| %>
                    <tr>
                        <td><%= bill.id %></td>
                        <td><%= bill.name %></td>
                        <td><%= bill.value %></td>
                        <td><%= bill.category.name %></td>
                        <td>
                            <%= link_to 'Edit', edit_bill_path(bill), class: 'btn btn-small btn-info' %>
                            <%= link_to 'Delete', bill, method: :delete, class: 'btn btn-small btn-danger' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/bills/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>New</h4>
    </div>

    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/categories/_form.html.erb
<%= form_for @category, html: { class: 'form'} do |f| %>
    <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
        <%= f.label :desc %>
        <%= f.text_area :desc, class: 'form-control' %>
    </div>
    <div class="form-group">
            <%= f.submit 'Save', :class => 'btn btn-success' %>
    </div>

<% end %>

RAILS-5-NA-PRATICA/app/app/views/categories/edit.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Edit</h4>
    </div>

    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/categories/index.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Categories</h4>    
    </div>
    <div class="panel-body">
        <%= link_to 'New Category', new_category_path ,class: 'btn btn-primary'%>
        <div class="table-responsive">
            <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Name</th>
                    <th>Description</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <% @categories.each do |category| %>
                    <tr>
                        <td><%= category.id %></td>
                        <td><%= category.name %></td>
                        <td><%= category.desc %></td>
                        <td>
                            <%= link_to 'Edit', edit_category_path(category), class: 'btn btn-small btn-info' %>
                            <%= link_to 'Delete', category, method: :delete, class: 'btn btn-small btn-danger' %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
            </table>
        </div>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/categories/new.html.erb
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>New</h4>
    </div>

    <div class="panel-body">
        <%= render 'form' %>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/dashboard/index.html.erb
<h4>Dashboard</h4>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Charts</h4>
    </div>
    <div class="panel-body">
        <%= bar_chart @bills.group(:value).count %>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Charts 2</h4>
    </div>
    <div class="panel-body">
        <%= column_chart @bills.group(:value).count %>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Charts 3</h4>
    </div>
    <div class="panel-body">
        <%= area_chart @bills.group(:value).count %>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-heading">
        <h4>Charts 4</h4>
    </div>
    <div class="panel-body">
        <%= pie_chart @bills.group(:value).count %>
    </div>
</div>

RAILS-5-NA-PRATICA/app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">App</a>  
        </div>

        <div class="collapse navbar-collapse" id="navbar">
          <ul class="nav navbar-nav">
            <li><a href="/" >Home</a></li>
            <li><a href="/categories" >Category</a></li>
            <li><a href="/bills" >Bills</a></li>
            <li class="dropdown">
              <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button">Menu <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="">Home</a></li>
              </ul>
            </li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <body>
    <main>
      <div class="container">
        <div class="row">
            <%= yield %>
        </div>
      </div>
    </main>
  </body>

  <footer id="footer" class="navbar-default">
    <ddiv class="container">
      <div class="row text-center">
        <p>&copy; All rights Reserved</p>
        
      </div>
    </ddiv>
  </footer>
</html>